// Code generated by protoc-gen-go. DO NOT EDIT.
// source: warrior.proto

// Explicitly declaring the generating package name.

package warrior

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Warrior_WeaponType int32

const (
	Warrior_KNIFE Warrior_WeaponType = 0
	Warrior_SWORD Warrior_WeaponType = 1
	Warrior_AXE   Warrior_WeaponType = 2
)

var Warrior_WeaponType_name = map[int32]string{
	0: "KNIFE",
	1: "SWORD",
	2: "AXE",
}

var Warrior_WeaponType_value = map[string]int32{
	"KNIFE": 0,
	"SWORD": 1,
	"AXE":   2,
}

func (x Warrior_WeaponType) String() string {
	return proto.EnumName(Warrior_WeaponType_name, int32(x))
}

func (Warrior_WeaponType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f32876558ada2f2b, []int{0, 0}
}

type Warrior struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Keyword repeated means dynamic array size.
	Weapons []*Warrior_Weapon `protobuf:"bytes,2,rep,name=weapons,proto3" json:"weapons,omitempty"`
	// Using import utilities.
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Warrior) Reset()         { *m = Warrior{} }
func (m *Warrior) String() string { return proto.CompactTextString(m) }
func (*Warrior) ProtoMessage()    {}
func (*Warrior) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32876558ada2f2b, []int{0}
}

func (m *Warrior) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Warrior.Unmarshal(m, b)
}
func (m *Warrior) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Warrior.Marshal(b, m, deterministic)
}
func (m *Warrior) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Warrior.Merge(m, src)
}
func (m *Warrior) XXX_Size() int {
	return xxx_messageInfo_Warrior.Size(m)
}
func (m *Warrior) XXX_DiscardUnknown() {
	xxx_messageInfo_Warrior.DiscardUnknown(m)
}

var xxx_messageInfo_Warrior proto.InternalMessageInfo

func (m *Warrior) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Warrior) GetWeapons() []*Warrior_Weapon {
	if m != nil {
		return m.Weapons
	}
	return nil
}

func (m *Warrior) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Warrior_Weapon struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Warrior_WeaponType `protobuf:"varint,2,opt,name=type,proto3,enum=warrior.Warrior_WeaponType" json:"type,omitempty"`
	Damage               int32              `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Warrior_Weapon) Reset()         { *m = Warrior_Weapon{} }
func (m *Warrior_Weapon) String() string { return proto.CompactTextString(m) }
func (*Warrior_Weapon) ProtoMessage()    {}
func (*Warrior_Weapon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32876558ada2f2b, []int{0, 0}
}

func (m *Warrior_Weapon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Warrior_Weapon.Unmarshal(m, b)
}
func (m *Warrior_Weapon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Warrior_Weapon.Marshal(b, m, deterministic)
}
func (m *Warrior_Weapon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Warrior_Weapon.Merge(m, src)
}
func (m *Warrior_Weapon) XXX_Size() int {
	return xxx_messageInfo_Warrior_Weapon.Size(m)
}
func (m *Warrior_Weapon) XXX_DiscardUnknown() {
	xxx_messageInfo_Warrior_Weapon.DiscardUnknown(m)
}

var xxx_messageInfo_Warrior_Weapon proto.InternalMessageInfo

func (m *Warrior_Weapon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Warrior_Weapon) GetType() Warrior_WeaponType {
	if m != nil {
		return m.Type
	}
	return Warrior_KNIFE
}

func (m *Warrior_Weapon) GetDamage() int32 {
	if m != nil {
		return m.Damage
	}
	return 0
}

type Army struct {
	Warriors             []*Warrior `protobuf:"bytes,1,rep,name=warriors,proto3" json:"warriors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Army) Reset()         { *m = Army{} }
func (m *Army) String() string { return proto.CompactTextString(m) }
func (*Army) ProtoMessage()    {}
func (*Army) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32876558ada2f2b, []int{1}
}

func (m *Army) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Army.Unmarshal(m, b)
}
func (m *Army) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Army.Marshal(b, m, deterministic)
}
func (m *Army) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Army.Merge(m, src)
}
func (m *Army) XXX_Size() int {
	return xxx_messageInfo_Army.Size(m)
}
func (m *Army) XXX_DiscardUnknown() {
	xxx_messageInfo_Army.DiscardUnknown(m)
}

var xxx_messageInfo_Army proto.InternalMessageInfo

func (m *Army) GetWarriors() []*Warrior {
	if m != nil {
		return m.Warriors
	}
	return nil
}

func init() {
	proto.RegisterEnum("warrior.Warrior_WeaponType", Warrior_WeaponType_name, Warrior_WeaponType_value)
	proto.RegisterType((*Warrior)(nil), "warrior.Warrior")
	proto.RegisterType((*Warrior_Weapon)(nil), "warrior.Warrior.Weapon")
	proto.RegisterType((*Army)(nil), "warrior.Army")
}

func init() { proto.RegisterFile("warrior.proto", fileDescriptor_f32876558ada2f2b) }

var fileDescriptor_f32876558ada2f2b = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xf3, 0x30,
	0x18, 0xc7, 0xdf, 0xb4, 0x5d, 0xfb, 0xee, 0xa9, 0x4a, 0xc9, 0x41, 0x4b, 0x3d, 0x58, 0x7a, 0x2a,
	0x28, 0x2d, 0x56, 0xaf, 0x1e, 0x06, 0x4e, 0x10, 0x41, 0x21, 0x4e, 0xea, 0x4d, 0x32, 0x1a, 0xcb,
	0x60, 0x5d, 0x42, 0x9a, 0x31, 0xfa, 0x79, 0xfc, 0xa2, 0xb2, 0xa4, 0x51, 0x10, 0x3d, 0xe5, 0xf9,
	0x27, 0x3f, 0xf2, 0xff, 0x25, 0x70, 0xb8, 0xa3, 0x52, 0xae, 0xb8, 0x2c, 0x84, 0xe4, 0x8a, 0xe3,
	0x60, 0x8c, 0xc9, 0x59, 0xcb, 0x79, 0xbb, 0x66, 0xa5, 0xde, 0x5e, 0x6e, 0xdf, 0x4b, 0xb5, 0xea,
	0x58, 0xaf, 0x68, 0x27, 0x0c, 0x99, 0x7d, 0x38, 0x10, 0xd4, 0x06, 0xc6, 0x18, 0xbc, 0x0d, 0xed,
	0x58, 0x8c, 0x52, 0x94, 0x4f, 0x89, 0x9e, 0xf1, 0x25, 0x04, 0x3b, 0x46, 0x05, 0xdf, 0xf4, 0xb1,
	0x93, 0xba, 0x79, 0x58, 0x9d, 0x14, 0xb6, 0xaa, 0xb6, 0xab, 0x3e, 0x27, 0x96, 0xc3, 0x37, 0x70,
	0xb0, 0xa6, 0xbd, 0x7a, 0xdb, 0x8a, 0x86, 0x2a, 0xd6, 0xc4, 0x6e, 0x8a, 0xf2, 0xb0, 0x4a, 0x0a,
	0xa3, 0x52, 0x58, 0x95, 0x62, 0x61, 0x55, 0x48, 0xb8, 0xe7, 0x5f, 0x0c, 0x9e, 0x30, 0xf0, 0xcd,
	0x8d, 0xbf, 0xfa, 0x94, 0xe0, 0xa9, 0x41, 0xb0, 0xd8, 0x49, 0x51, 0x7e, 0x54, 0x9d, 0xfe, 0x21,
	0xb3, 0x18, 0x04, 0x23, 0x1a, 0xc4, 0xc7, 0xe0, 0x37, 0xb4, 0xa3, 0x2d, 0xd3, 0x1e, 0x13, 0x32,
	0xa6, 0xec, 0x1c, 0xe0, 0x9b, 0xc5, 0x53, 0x98, 0x3c, 0x3c, 0xde, 0xdf, 0xcd, 0xa3, 0x7f, 0xfb,
	0xf1, 0xb9, 0x7e, 0x22, 0xb7, 0x11, 0xc2, 0x01, 0xb8, 0xb3, 0xd7, 0x79, 0xe4, 0x64, 0xd7, 0xe0,
	0xcd, 0x64, 0x37, 0xe0, 0x0b, 0xf8, 0x3f, 0x16, 0xf6, 0x31, 0xd2, 0xdf, 0x11, 0xfd, 0x34, 0x20,
	0x5f, 0xc4, 0xd2, 0xd7, 0x4f, 0xbd, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x24, 0xcb, 0xc6, 0xfe,
	0x9d, 0x01, 0x00, 0x00,
}
